[package]
name = "virus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.9.0"
log = "0.4.14"
winit = "0.26.1"
rand = "0.8.4"
rayon = "1.5.1"
winit_input_helper = "0.11.0"